Update the scripts to use (a lot of) functions

diff --git a/bin/stop-instance b/bin/stop-instance
--- a/bin/stop-instance
+++ b/bin/stop-instance
@@ -1,20 +1,21 @@
 #!/bin/bash
 
-set -e
-set -u
-set -o errexit
+source "$(dirname $0)/functions.sh"
+
+$(fail_on_nontrue_return_value)
+$(fail_on_unbound_variables)
 
 bin_name=$(basename $0)
 usage="Usage: ${bin_name} <instance path>
 
 Example: ${bin_name} ~/slapd-test"
 
-(test "$1" = "-h" || test "$1" = "--help") && {
+want_help $1 && {
   echo "$usage"
   exit 0
 }
 
-test "$#" -ne 1 && {
+not_equal $# 1 && {
   echo "ERROR: Invalid amount of arguments $#, need 1."
   echo ""
   echo "$usage"
@@ -23,21 +24,16 @@ test "$#" -ne 1 && {
 
 instance_path=$1
 instance_name="$(basename $instance_path)"
-
 instance_port=3389
+canonical_instance_path=$(canonical_path "${instance_path}")
 
 set +u
-test "$SLAPD_PORT" = "" && {
+not_empty "$SLAPD_PORT" && {
   instance_port=$SLAPD_PORT
 }
 set -u
 
-# Get canonical instance path
-pushd "${instance_path}" > /dev/null
-canonical_instance_path=`pwd -P`
-popd > /dev/null
-
-ls "${canonical_instance_path}/run" &> /dev/null || {
+exists_not "${canonical_instance_path}/run" && {
   echo "ERROR: Given instance path is invalid as it has no run/ directory."
   echo ""
   echo "Please supply a valid instance path created by 'new-instance'"
@@ -46,15 +42,15 @@ ls "${canonical_instance_path}/run" &> /dev/null || {
 
 pid_file="${canonical_instance_path}/run/slapd.pid"
 
-ls "${pid_file}" &> /dev/null && {
-  pid=$(cat $pid_file)
-
-  kill -0 $pid && {
-    kill -INT $pid
-    echo "Sent interrupt signal to instance ${instance_name} (pid ${pid})"
-    exit 0
-  }
+exists_not "${pid_file}" && {
+  echo "Instance ${instance_name} is not running. Cannot kill it."
+  exit 1 
 }
 
-echo "Instance ${instance_name} is not running. Cannot kill it."
-exit 1 
+pid=$(cat $pid_file)
+
+kill -0 $pid && {
+  kill -INT $pid
+  echo "Sent interrupt signal to instance ${instance_name} (pid ${pid})"
+  exit 0
+}
